---
abstract: 'Read/Write Vixie compatible crontab(5) files'
author:
  - 'Scott Wiersdorf <scott@perlcode.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Crontab
no_index:
  directory:
    - t
    - inc
requires: {}
version: 1.40
